name: Qameta • It's all about tests
description: It's all about tests
url: https://qameta.io

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

timezone: Europe/Moscow

gems:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-avatar

sass:
  style: compressed

exclude:
  - README.md
  - docker-compose.yml
  - .gitignore
  - .idea
