name: Qameta • It's all about tests
description: It's all about tests
url: https://qameta.io

markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

social:
  github: https://github.com/qameta

timezone: Europe/Moscow

exclude:
  - README.md
  - docker-compose.yml
  - .gitignore
  - .idea
