---
baseURL: "http://qameta.io/"
title: "Qameta"
permalinks:
  blog: /:section/:year/:month/:filename/
canonifyurls: true
paginate: 2
LanguageCode: "en_EN"
theme: "casper"
Copyright: © 2017
DisqusShortname: qameta

verbose:                    true
verboseLog:                 true

params:
  description: "Software Development and Quality"
  author: "Qameta team"
  githubName: "qameta"
  cover: "images/bg.jpg"
  hideHUGOSupport: true
  customCSS: ["css/custom.css"]
  customHeaderPartial: "header-hilightjs.html"
menu:
  top:
    - Name: "Home"
      Weight: -120
      Identifier: "home"
      URL: "/"
    - Name: "Blog"
      Weight: -110
      Identifier: "blog"
      URL: "/blog/"
  main:
    - Name: "Home"
      Weight: -120
      Identifier: "home"
      URL: "/"
    - Name: "Blog"
      Weight: -110
      Identifier: "blog"
      URL: "/blog/"
