---
baseURL: "http://qameta.io/"
title: "Qameta"
permalinks:
  post: /:year/:month/:title/
canonifyurls: true
params:
  description: "Software Development and Quality"
  author: "Qameta team"
  githubName: "qameta"
  cover: "images/bg.jpg"
  hideHUGOSupport: true
menu:
  main:
      - Name: "Home"
        Weight: -120
        Identifier: "home"
        URL: "/"
      - Name: "Blog"
        Weight: -110
        Identifier: "blog"
        URL: "/blog/"
      - Name: "About"
        Weight: -100
        URL: "/about/"
