version: '2'

networks:
  qameta:
    driver: bridge

services:
  site:
    image: jekyll/jekyll
    command: 'jekyll serve'
    ports:
      - '4000:4000'
    volumes:
      - '$PWD:/srv/jekyll'
    networks:
      - 'qameta'
